### ISSUE TITLE
[Icon request] - Bedrock files

### ISSUE THREAD

**Issue by MetalManeMc** [FuncFusion/mc-dp-icons#14]
Hello,
I create add-ons, the Bedrock equivalent to Data Packs, and I've been using this extension for some time because the icons work 90% of the time.
There are nevertheless some missing elements I noticed, most of which are just because they have a different name.
Here are the ones I caught:
- Subfolders:
  - Missing name support
    - `entities` and `entity` folders which store entity information, which can just reuse `wolf_variant` folder texture
    - `items` folder which can reuse `item_modifier` folder texture
    - `ui` which could use `painting_variant` texture
  - <details><summary>Missing textures</summary>
    - `blocks` folder<br>
    - `trading` folder<br>
    - `spawn_rules` folder<br>
    - `animation_controllers` folder<br>
    - `animations` folder<br>
    - `attachables` folder (ie. armor)<br>
    - `fogs` folder<br>
    - `render_controllers` folder (controls how entities are rendered)</details>
- Files:
  - Missing name support
    - `manifest.json`, which should reuse `pack.mcmeta`
    - `languages.json` files, which should reuse the lang __folder__ icon
    - `.png` folder in `fonts` should also use the `.json` in font folder texture
    - files in `entity` and `entities` could reuse the textures used inside `wolf_variants` folders
    - files in `items` could reuse the textures used inside `item_modifier` folders
  - <details><summary>Missing textures</summary>
    - `.mcworld` file type<br>
    - `biomes_client.json`<br>
    - `language_names.json`<br>
    - `terrain_textures.json` (block textures)<br>
    - `blocks.json` (block sounds & textures)<br>
 </details>

I added all the missing textures in case you decide to have official add-on support in your pack, but if you could just have some more file names pointing to the already existing textures is would be amazing!

**Comment by SuperAnt220** [comment]
Thank you for this, we will consider adding these in 4.0

**Comment by SuperAnt220** [comment]
I think we've added icons for everything 👍
