### ISSUE TITLE
Icons simply do not apply

### ISSUE THREAD

**Issue by FracturedFlux** [FuncFusion/mc-dp-icons#7]
https://github.com/SuperAnt220/mc-dp-icons/assets/131806616/ca1638dc-a7a4-4e13-acb0-febafdf4103a
Every time I try to enable the extension or set the file icon theme, it just gives the error "Problems parsing file icons file: End of file expected"

**Comment by eggohito** [comment]
I was having the same issue as well, but it seems to have fixed itself when I re-installed the extension

**Comment by SuperAnt220** [comment]
This bug shouldn't happen again
