### ISSUE TITLE
Do not create .vscode/settings.json with pack.mcmeta check if MCDP Icons is not the default icon theme

### ISSUE THREAD

**Issue by thonkinator** [FuncFusion/mc-dp-icons#8]
The setting called "Enable Pack Mcmeta check" will always create the .vscode/settings.json folder with the icon pack setting, even if it is not needed. In my case, I use the vscode-icons pack by default, so this setting is not needed and actually clutters up projects. I think this setting should only be created if MCDP icons _is_ the default theme (and if this feature is on, obviously).

**Comment by SuperAnt220** [comment]
Resolved this in 3.1.0
