### ISSUE TITLE
sub sub folders

### ISSUE THREAD

**Issue by PiggyPigCute** [FuncFusion/mc-dp-icons#9]
Hi 👋 I don't know is this issue is easy to resolve but:

When an Item Modifier (json file) isn't directly in the `item_modifiers` folder but in a sub-folder of this folder, it doesn't have the item modifier icon (cf: picture)

It's the same thing with dimensions, dimension_types, predicates, recipes, damage_types...

![image](https://github.com/SuperAnt220/mc-dp-icons/assets/98620482/0580f0d7-490e-4477-b890-9a6995eeea12)

**Comment by PiggyPigCute** [comment]
Oh, it seems more difficult than i thought

![image](https://github.com/SuperAnt220/mc-dp-icons/assets/98620482/d57ca6fd-0123-4032-a3b1-6bf4377bb87d)

This issue can't be directly resolved in the fileicon file 😭

**Comment by SuperAnt220** [comment]
Yea we plan to support this type of stuff in 4.0
